import { PagesFunction, D1Database } from "@cloudflare/workers-types";

interface Env {
  DB: D1Database;
}

interface AssetRow {
  id: string;
  title: string;
  description: string;
  slug: string;
  asset_id: string | null;
}

export const onRequest: PagesFunction<Env> = async (context) => {
  const { env } = context;
  const baseUrl = "https://huepress.co";

  try {
    // query assets
    const { results } = await env.DB.prepare(
      "SELECT id, title, description, slug, asset_id FROM assets WHERE status = 'published' ORDER BY title ASC"
    ).all<AssetRow>();

    let markdown = `# HuePress Full Catalog\n\n`;
    markdown += `This document contains a comprehensive list of all coloring pages available on HuePress.\n\n`;
    
    markdown += `## Coloring Pages\n\n`;

    if (results && results.length > 0) {
      markdown += results.map(asset => {
         const slug = asset.slug || "design";
         const id = asset.asset_id || asset.id;
         const url = `${baseUrl}/coloring-pages/${slug}-${id}`;
         const description = asset.description ? `: ${asset.description}` : "";
         return `* [${asset.title}](${url})${description}`;
      }).join("\n");
    } else {
      markdown += "No coloring pages currently available.";
    }

    markdown += `\n\n---\nGenerated by HuePress dynamic catalog system.`;

    return new Response(markdown, {
      headers: {
        "Content-Type": "text/markdown; charset=UTF-8",
        "Cache-Control": "public, max-age=3600",
      },
    });

  } catch (err) {
    console.error("llms-full.txt generation error:", err);
    return new Response("# Error generating catalog\n\nPlease try again later.", { 
      status: 500,
      headers: { "Content-Type": "text/markdown" }
    });
  }
};
